accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [

    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

likeapp/urls.py
from django.urls import path

from likeapp.views import LikeArticleView

app_name = 'likeapp'

urlpatterns = [
    path('article/like/<int:pk>', LikeArticleView.as_view(), name='article_like'),
]

postapp/urls.py
from django.urls import path

from postapp import views
from postapp.views import PostListView, PostCreateView, PostDetailView, PostUpdateView, PostDeleteView

app_name = 'postapp'

urlpatterns = [
    path('list/', PostListView.as_view(), name='list'),
    path('create/', PostCreateView.as_view(), name='create'),
    path('detail/<int:pk>', PostDetailView.as_view(), name='detail'),
    path('update/<int:pk>', PostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', PostDeleteView.as_view(), name='delete'),

    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),
    ]

radhelper/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),

    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('boards/', include('boardapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
    path('storages/', include('storageapp.urls')),
    path('storagecomments/', include('storagecommentapp.urls')),
    path('posts/', include('postapp.urls')),
    path('postcomments/', include('postcommentapp.urls')),
    path('likes/', include('likeapp.urls')),
    path('unlikes/', include('unlikeapp.urls')),
    path('summernote/', include('django_summernote.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

postapp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager


class Post(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='post', null=True)
    title = models.CharField(max_length=200, null=False)

    tags = TaggableManager(blank=True)
    modify_dt = models.DateTimeField('MODIFY DATE', auto_now=True)

    content = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    hits = models.PositiveIntegerField(default=0)

    like = models.IntegerField(default=0)
    unlike = models.IntegerField(default=0)

    def get_absolute_url(self):
        return reverse('postapp:detail', args=[self.id])

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'post'

postapp/forms.py
import taggit.views
from django.forms import ModelForm
from django import forms
from django_summernote.fields import SummernoteTextField
from django_summernote.widgets import SummernoteWidget
from postapp.models import Post
from taggit.forms import *

categories =(
    ('구인구직', '구인구직'),
    ('경제', '경제'),
    ('정치', '정치'),
    ('기타', '기타'),
)

class PostCreationForm(ModelForm):
    title = forms.CharField(
        label='글 제목',
        widget=forms.TextInput(
            attrs={
                'placeholder' : '게시글 제목',
            }
        ),
        required=True,
    )

    content = SummernoteTextField()

    field_order = [
        'title',
        'tags',
        'content',
    ]


    class Meta:
        model = Post
        fields = [
            'title',
            'content',
            'tags',
        ]
        widgets = {
            'content': SummernoteWidget(attrs={'summernote': {
                'width':'100%',
                'height':'400px',
                'attachment_filesize_limit': 10 * 1024 * 1024,
            }}),
            'tags': forms.Select(choices=categories)
        }

    def clean(self):
        cleaned_data = super().clean()

        title = cleaned_data.get('title', '')
        content =  cleaned_data.get('content', '')

        if title == '':
            self.add_error('title', '글제목을 입력하세요')
        elif content == '':
            self.add_error('content', '글내용을 입력하세요')
        else:
            self.title = title
            self.content = content

postapp/views.py
import mimetypes
import os

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import UserPassesTestMixin
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import get_object_or_404

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView, TemplateView
from django.views.generic.edit import FormMixin
from django.http import HttpResponse, Http404

from postapp.decorators import post_ownership_required
from postapp.forms import PostCreationForm
from postapp.models import Post
from commentapp.forms import CommentCreationForm


@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
class PostCreateView(UserPassesTestMixin, CreateView):
    model = Post
    form_class = PostCreationForm
    template_name = 'postapp/create.html'

    def test_func(self):
        return self.request.user.is_staff

    def form_valid(self, form):
        temp_post = form.save(commit=False)
        temp_post.writer = self.request.user
        temp_post.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('postapp:detail', kwargs={'pk': self.object.pk})

class PostDetailView(DetailView):
    model = Post
    context_object_name = 'target_post'
    template_name = 'postapp/detail.html'


@method_decorator(post_ownership_required, 'get')
@method_decorator(post_ownership_required, 'post')
class PostUpdateView(UpdateView):
    model = Post
    context_object_name = 'target_post'
    form_class = PostCreationForm
    template_name = 'postapp/update.html'

    def get_success_url(self):
        return reverse('postapp:detail', kwargs={'pk': self.object.pk})

class PostDetailView(DetailView, FormMixin):
    model = Post
    form_class = CommentCreationForm
    context_object_name = 'target_post'
    template_name = 'postapp/detail.html'

@method_decorator(post_ownership_required, 'get')
@method_decorator(post_ownership_required, 'post')
class PostDeleteView(DeleteView):
    model = Post
    context_object_name = 'target_post'
    success_url = reverse_lazy('postapp:list')
    template_name = 'postapp/delete.html'

@method_decorator(login_required, 'get')
class PostListView(UserPassesTestMixin, ListView):
    model = Post
    context_object_name = 'post_list'
    template_name = 'postapp/list.html'
    paginate_by = 10

    def test_func(self):
        return self.request.user.is_staff

    def get_queryset(self):

        search_keyword = self.request.GET.get('q', '')
        search_type = self.request.GET.get('type', '')
        post_list = Post.objects.order_by('-id')

        if search_keyword:
            if len(search_keyword) > 1:
                if search_type == 'all':
                    search_post_list = post_list.filter(
                        Q(title__icontains=search_keyword) | Q(content__icontains=search_keyword) | Q(
                            writer__profile__nickname__icontains=search_keyword))
                elif search_type == 'title_content':
                    search_post_list = post_list.filter(
                        Q(title__icontains=search_keyword) | Q(content__icontains=search_keyword))
                elif search_type == 'title':
                    search_post_list = post_list.filter(title__icontains=search_keyword)
                elif search_type == 'content':
                    search_post_list = post_list.filter(content__icontains=search_keyword)
                elif search_type == 'writer':
                    search_post_list = post_list.filter(writer__profile__nickname__icontains=search_keyword)

                return search_post_list
            else:
                messages.error(self.request, '검색어는 2글자 이상 입력해주세요.')
        return post_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = context['paginator']
        page_numbers_range = 5
        max_index = len(paginator.page_range)

        page = self.request.GET.get('page')
        current_page = int(page) if page else 1

        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index

        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range

        search_keyword = self.request.GET.get('q', '')
        search_type = self.request.GET.get('type', '')

        if len(search_keyword) > 1:
            context['q'] = search_keyword
        context['type'] = search_type

        return context


class TagCloudTV(TemplateView):
    template_name = 'taggit/taggit_cloud.html'


class TaggedObjectLV(ListView):
    template_name = 'taggit/taggit_post_list.html'
    model = Post

    def get_queryset(self):
        return Post.objects.filter(tags__name=self.kwargs.get('tag'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tagname'] = self.kwargs['tag']
        return context

postapp/templates/postapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">

    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>Create Post</h4>
        </div>
        <form action="{% url 'postapp:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-3 mt-3">
        </form>
    </div>

<script>var editor = new MediumEditor('.editable');</script>

{% endblock %}

postapp/templates/postapp/delete.html
{% extends 'base.html' %}
{% block content %}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>Delete Post : {{ target_post.title }}</h4>
        </div>
        <form action="{% url 'postapp:delete' pk=target_post.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-secondary rounded-pill col-3 mt-3">
        </form>
    </div>

{% endblock %}

postapp/templates/postapp/detail.html
{% extends 'base.html' %}

{% block content %}

  <div>
    <div style="text-align: center; max-width: 700px; margin: 4rem auto;">
      <h1>
        {{ target_post.title }}
      </h1>
      <span>
        <b>TAG</b> <i class="fas fa-tag"></i>
        {% load taggit_templatetags2_tags %}
        {% get_tags_for_object object as "tags" %}

        {% for tag in tags %}
        <a href="{% url 'postapp:tagged_object_list' tag.name %}">{{tag.name}}</a>
        {% endfor %}
      </span>
      <div style="vertical-align: middle; text-align: left; margin: 0.4rem; margin-top: 0.3rem">
        <div style="text-align: center; box-shadow: #d4d4d4 0px 0px 5px; border-radius: 10rem;
            display: inline-block;">
          <a href="{% url 'accountapp:detail' pk=target_post.writer.pk %}">
            <img style="display: inline-block;    width: 2rem; height: 2rem; object-fit: cover;
                        border-radius: 10rem; box-shadow: #cccccc 0px 0px 5px;
                         margin: .3rem -0.3rem .3rem .3rem"
                    src="{{ target_post.writer.profile.image.url }}" alt="">
            <p style="text-align: center; vertical-align: middle; display: inline-block;
                font-family: 'NanumSquareB', sans-serif; font-size: 1.1rem;
                 margin: 0.3rem 0.6rem 0.3rem 0.6rem;">{{ target_post.writer.profile.nickname }}</p>
          </a>
        </div>
          <span class='text-muted'>
            <i style="vertical-align: middle; font-size: 1.2rem; margin: 0 .5em;"
               class="material-icons">
                schedule
            </i>
            {{ target_post.created_at }}
          </span>
      </div>

      <hr>

      <div class="text-left">
        {{ target_post.content | safe }}
      </div>

      {% if target_post.writer == user %}
      <a href="{% url 'postapp:update' pk=target_post.pk %}"
      class="btn btn-primary rounded-pill col-3 mt-3">
        Update
      </a>
      <a href="{% url 'postapp:delete' pk=target_post.pk %}"
      class="btn btn-secondary rounded-pill col-3 mt-3">
        Delete
      </a>
      {% endif %}
      <hr>

      {% for postcomment in target_post.postcomment.all %}
        {% include 'postcommentapp/detail.html' with postcomment=postcomment %}
      {% endfor %}

      {% include 'postcommentapp/create.html' with post=target_post %}
    </div>
  </div>
<br>


{% endblock %}

postapp/templates/postapp/list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="container my-3">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col" style="text-align: center">제목</th>
                    <th scope="col">글쓴이</th>
                    <th scope="col">날짜</th>
                </tr>
            </thead>
            <tbody>
            {% for post in post_list %}
            {% if post in jobs_boards %}
            <tr>
                 <td>
                    <a href="{% url 'postapp:detail' pk=post.pk %}">
                           [구인구직] {{ post.title }}
                    </a>
                    <span>
                        <i style="vertical-align: middle; font-size: 1.2rem; margin: 0 .5em;"
                        class="material-icons">
                            question_answer
                        </i>
                            {{ post.postcomment.count }}
                    </span>
                </td>
                <td>
                    {{ post.writer.profile.nickname }}
                </td>
                <td>
                    {{ post.created_at }}
                </td>
            </tr>
            {% elif post in posts_boards %}
            <tr>
                 <td>
                    <a href="{% url 'postapp:detail' pk=post.pk %}">
                           {{ post.title }}
                    </a>
                    <span>
                        <i style="vertical-align: middle; font-size: 1.2rem; margin: 0 .5em;"
                        class="material-icons">
                            question_answer
                        </i>
                            {{ post.postcomment.count }}
                    </span>
                </td>
                <td>
                    {{ post.writer.profile.nickname }}
                </td>
                <td>
                    {{ post.created_at }}
                </td>
            </tr>
            {% endif %}
            {% endfor %}
            </tbody>
        </table>
    </div>
    {% include 'snippets/pagination.html' with page_obj=page_obj %}
    <div style="text-align: center">
        <a href="{% url 'postapp:create' %}" class="btn btn-dark rounded-pill col-3 mt-3 px-2">
            Create Post
        </a>
    </div>

{% endblock %}

postapp/templates/postapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">

    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>Post Update</h4>
        </div>
        <form action="{% url 'postapp:update' pk=target_post.pk %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-3 mt-3">
        </form>
    </div>

<script>var editor = new MediumEditor('.editable');</script>

{% endblock %}