accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [

    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]

likeapp/urls.py
from django.urls import path

from likeapp.views import LikeArticleView

app_name = 'likeapp'

urlpatterns = [
    path('article/like/<int:pk>', LikeArticleView.as_view(), name='article_like'),
]

postapp/urls.py
from django.urls import path

from postapp import views
from postapp.views import PostListView, PostCreateView, PostDetailView, PostUpdateView, PostDeleteView

app_name = 'postapp'

urlpatterns = [
    path('list/', PostListView.as_view(), name='list'),
    path('create/', PostCreateView.as_view(), name='create'),
    path('detail/<int:pk>', PostDetailView.as_view(), name='detail'),
    path('update/<int:pk>', PostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', PostDeleteView.as_view(), name='delete'),

    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),
    ]

projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectListView, ProjectCreateView, ProjectDetailView, ProjectDeleteView

app_name = 'projectapp'

urlpatterns = [
    path('list/', ProjectListView.as_view(), name='list'),
    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),
    path('delete/<int:pk>', ProjectDeleteView.as_view(), name='delete'),
]

radhelper/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),

    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('boards/', include('boardapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
    path('storages/', include('storageapp.urls')),
    path('storagecomments/', include('storagecommentapp.urls')),
    path('posts/', include('postapp.urls')),
    path('postcomments/', include('postcommentapp.urls')),
    path('likes/', include('likeapp.urls')),
    path('unlikes/', include('unlikeapp.urls')),
    path('summernote/', include('django_summernote.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}


<body style="font-family: 'NanumSquareR';">

    {% include 'header.html' %}

    <hr>

    {% for message in messages %}

    <div class="text-center">
        <div class="btn btn-{{message.tags}} rounded-pill px-5 my-3">
            {{ message }}
        </div>
    </div>

    {% endfor %}

    {% block content %}
    {% endblock %}

    <hr>

    {% include 'footer.html' %}

<script>
    document.addEventListener('DOMContentLoaded', e => {

        const searchForm = document.getElementById('search-form');

        for (const check of document.getElementsByName('tags2')) {
            check.addEventListener('change', () => {
                searchForm.submit();
            });
        }
    });
</script>

</body>
</html>

templates/footer.html
<div class="radhelper_footer">
    <div class="radhelper_footer_button">
        <span>With Us</span> |
        <span>Contact Us : radcrews@gmail.com</span>
    </div>
    <div style="margin-top: 1rem;">
        <a href="{% url 'articleapp:list' %}">
            <h7 class="radhelper_logo">RadCrews</h7>
        </a>
    </div>
</div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>RadCrews</title>

    <!--  BOOTSTRAP LINK  -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

    <!--  GOOGLE FONT LINK  -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet">

    <!--  GOOGLE MATERIAL ICONS  -->
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons"
      rel="stylesheet">

    <!-- DEFAULT CSS LINK   -->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    <style>
        @font-face {
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareB';
            src: local('NanumSquareB'),
            url("{% static 'fonts/NanumSquareB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareEB';
            src: local('NanumSquareEB'),
            url("{% static 'fonts/NanumSquareEB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareL';
            src: local('NanumSquareL'),
            url("{% static 'fonts/NanumSquareL.otf' %}") format("opentype");
        }
        a { text-decoration:none }
    </style>
</head>

templates/header.html
<div class="radhelper_header">
    <div>
        <div>
            <a href="{% url 'articleapp:list' %}">
                <h3 class="radhelper_logo">RadCrews</h3>
            </a>
        </div>
        <div style="text-align: right; margin: 0 1rem;">
            {% if not user.is_authenticated %}
            <a href="{% url 'accountapp:create' %}" class="btn btn-outline-dark">
                <span>SignUp</span>
            </a>
            <a href="{% url 'accountapp:login' %}" class="btn btn-outline-dark">
                <span>Login</span>
            </a>
            {% else %}
            <a href="{% url 'accountapp:detail' pk=user.pk %}" class="btn btn-outline-dark">
                <span>MyPage</span>
            </a>
            <a href="{% url 'accountapp:logout' %}" class="btn btn-outline-dark">
                <span>Logout</span>
            </a>
            {% endif %}
        </div>
    </div>
    <div class="radhelper_header_navbar">
        <a href="{% url 'articleapp:list' %}" class="radhelper_header_nav">
            <span>Help me!</span>
        </a>
        <a href="{% url 'projectapp:list' %}" class="radhelper_header_nav">
            <span>Specialty</span>
        </a>
        <a href="{% url 'subscribeapp:list' %}" class="radhelper_header_nav">
            <span>Subscription</span>
        </a>

        <a href="{% url 'postapp:list' %}" class="radhelper_header_nav">
            <span>Board</span>
        </a>
    </div>
</div>

templates/withus.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<h1>메일로 병원 로고와 홈페이지 주소를 보내주시면, 배너로 만들어 드립니다.</h1>
{% endblock %}