accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [

    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]

likeapp/urls.py
from django.urls import path

from likeapp.views import LikeArticleView

app_name = 'likeapp'

urlpatterns = [
    path('article/like/<int:pk>', LikeArticleView.as_view(), name='article_like'),
]

radhelper/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),

    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('boards/', include('boardapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
    path('storages/', include('storageapp.urls')),
    path('storagecomments/', include('storagecommentapp.urls')),
    path('posts/', include('postapp.urls')),
    path('postcomments/', include('postcommentapp.urls')),
    path('likes/', include('likeapp.urls')),
    path('unlikes/', include('unlikeapp.urls')),
    path('summernote/', include('django_summernote.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from projectapp.models import Project


class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='article', null=True)
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, related_name='article', null=True)

    title = models.CharField(max_length=200, null=False)

    image = models.ImageField(upload_to='article/%Y/%m/%d', null=False)
    image2 = models.ImageField(upload_to='article/%Y/%m/%d', null=True, blank=True)
    image3 = models.ImageField(upload_to='article/%Y/%m/%d', null=True, blank=True)
    image4 = models.ImageField(upload_to='article/%Y/%m/%d', null=True, blank=True)
    image5 = models.ImageField(upload_to='article/%Y/%m/%d', null=True, blank=True)

    content = models.TextField(null=True)

    created_at = models.DateTimeField(auto_now_add=True, null=True)

    like = models.IntegerField(default=0)
    unlike = models.IntegerField(default=0)

articleapp/forms.py
from django.forms import ModelForm
from django import forms

from articleapp.models import Article
from projectapp.models import Project


class ArticleCreationForm(ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={'class': 'editable',
                                                           'style': 'height: auto; text-align: left;'}))
    project = forms.ModelChoiceField(Project.objects.all(), label="Specialty", required=False, empty_label="Selected Specialty")

    class Meta:
        model = Article
        fields = ['title', 'project', 'image', 'image2', 'image3', 'image4', 'image5','content']

articleapp/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.db.models import Q
from django.shortcuts import render
from django.contrib.auth.mixins import UserPassesTestMixin

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView
from django.views.generic.edit import FormMixin

from articleapp.decorators import article_ownership_required
from articleapp.forms import ArticleCreationForm
from articleapp.models import Article
from commentapp.forms import CommentCreationForm




@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
class ArticleCreateView(UserPassesTestMixin, CreateView):
    model = Article
    form_class = ArticleCreationForm
    template_name = 'articleapp/create.html'
    permission_denied_message = "인증 후 이용 가능합니다"

    def test_func(self):
        return self.request.user.is_staff

    def form_valid(self, form):
        temp_article = form.save(commit=False)
        temp_article.writer = self.request.user
        temp_article.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('articleapp:detail', kwargs={'pk': self.object.pk})

class ArticleDetailView(DetailView):
    model = Article
    context_object_name = 'target_article'
    template_name = 'articleapp/detail.html'


@method_decorator(article_ownership_required, 'get')
@method_decorator(article_ownership_required, 'post')
class ArticleUpdateView(UpdateView):
    model = Article
    context_object_name = 'target_article'
    form_class = ArticleCreationForm
    template_name = 'articleapp/update.html'

    def get_success_url(self):
        return reverse('articleapp:detail', kwargs={'pk': self.object.pk})

class ArticleDetailView(DetailView, FormMixin):
    model = Article
    form_class = CommentCreationForm
    context_object_name = 'target_article'
    template_name = 'articleapp/detail.html'

@method_decorator(article_ownership_required, 'get')
@method_decorator(article_ownership_required, 'post')
class ArticleDeleteView(DeleteView):
    model = Article
    context_object_name = 'target_article'
    success_url = reverse_lazy('articleapp:list')
    template_name = 'articleapp/delete.html'

@method_decorator(login_required, 'get')
class ArticleListView(UserPassesTestMixin, ListView):
    model = Article
    context_object_name = 'article_list'
    template_name = 'articleapp/list.html'
    paginate_by = 10

    def test_func(self):
        return self.request.user.is_staff

    def get_queryset(self):
        search_keyword = self.request.GET.get('q', '')
        search_type = self.request.GET.get('type', '')
        article_list = Article.objects.order_by('-id')

        if search_keyword:
            if len(search_keyword) > 1:
                if search_type == 'all':
                    search_article_list = article_list.filter(
                        Q(title__icontains=search_keyword) | Q(content__icontains=search_keyword) | Q(
                            writer__profile__nickname__icontains=search_keyword))
                elif search_type == 'title_content':
                    search_article_list = article_list.filter(
                        Q(title__icontains=search_keyword) | Q(content__icontains=search_keyword))
                elif search_type == 'title':
                    search_article_list = article_list.filter(title__icontains=search_keyword)
                elif search_type == 'content':
                    search_article_list = article_list.filter(content__icontains=search_keyword)
                elif search_type == 'writer':
                    search_article_list = article_list.filter(writer__profile__nickname__icontains=search_keyword)

                return search_article_list
            else:
                messages.error(self.request, '검색어는 2글자 이상 입력해주세요.')
        return article_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        paginator = context['paginator']
        page_numbers_range = 5
        max_index = len(paginator.page_range)

        page = self.request.GET.get('page')
        current_page = int(page) if page else 1

        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index

        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range

        search_keyword = self.request.GET.get('q', '')
        search_type = self.request.GET.get('type', '')

        if len(search_keyword) > 1:
            context['q'] = search_keyword
        context['type'] = search_type

        return context

articleapp/templates/articleapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">

    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>Ask a Question</h4>
        </div>
        <form action="{% url 'articleapp:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-3 mt-3">
        </form>
    </div>

<script>var editor = new MediumEditor('.editable');</script>

{% endblock %}

articleapp/templates/articleapp/delete.html
{% extends 'base.html' %}
{% block content %}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>Delete Question : {{ target_article.title }}</h4>
        </div>
        <form action="{% url 'articleapp:delete' pk=target_article.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-secondary rounded-pill col-3 mt-3">
        </form>
    </div>

{% endblock %}

articleapp/templates/articleapp/detail.html
{% extends 'base.html' %}

{% block content %}

  <div>
    <div style="text-align: center; max-width: 700px; margin: 4rem auto;">
      <h1>
        {{ target_article.title }}
      </h1>
      <div style="height: 2rem;">
        <a href="{% url 'likeapp:article_like' pk=target_article.pk %}">
          <i style="vertical-align: middle; font-size: 1.2rem;"
            class="material-icons">
            thumb_up_off_alt
          </i>
        </a>
        <span style="vertical-align: middle; font-size: 1.2rem; margin: 0 .5em;">
          {{ target_article.like }}
        </span>
      </div>
      <div style="vertical-align: middle; text-align: left; margin: 0.4rem; margin-top: 0.3rem">
        <div style="text-align: center; box-shadow: #d4d4d4 0px 0px 5px; border-radius: 10rem;
            display: inline-block;">
          <a href="{% url 'accountapp:detail' pk=target_article.writer.pk %}">
            <img style="display: inline-block;    width: 2rem; height: 2rem; object-fit: cover;
                      border-radius: 10rem; box-shadow: #cccccc 0px 0px 5px;
                       margin: .3rem -0.3rem .3rem .3rem"
                  src="{{ target_article.writer.profile.image.url }}" alt="">
            <p style="text-align: center; vertical-align: middle; display: inline-block;
              font-family: 'NanumSquareB', sans-serif; font-size: 1.1rem;
               margin: 0.3rem 0.6rem 0.3rem 0.6rem;">{{ target_article.writer.profile.nickname }}</p>
          </a>


        </div>
          <span class='text-muted'>
            <i style="vertical-align: middle; font-size: 1.2rem; margin: 0 .5em;"
               class="material-icons">
                schedule
            </i>
            {{ target_article.created_at }}
          </span>
      </div>
      <hr>

      <img style="width: 100%; border-radius: 1rem; margin: 0.1rem 0;"
              src="{{ target_article.image.url }}" alt="">
      {% if target_article.image2 %}
        <img style="width: 100%; border-radius: 1rem; margin: 0.1rem 0;"
               src="{{ target_article.image2.url }}" alt="">
      {% endif %}

      {% if target_article.image3 %}
        <img style="width: 100%; border-radius: 1rem; margin: 0.1rem 0;"
                src="{{ target_article.image3.url }}" alt="">
      {% endif %}

      {% if target_article.image4 %}
        <img style="width: 100%; border-radius: 1rem; margin: 0.1rem 0;"
                src="{{ target_article.image4.url }}" alt="">
      {% endif %}

      {% if target_article.image5 %}
        <img style="width: 100%; border-radius: 1rem; margin: 0.1rem 0;"
                src="{{ target_article.image5.url }}" alt="">
      {% endif %}


      <div class="text-left">
        {{ target_article.content | safe }}
      </div>

      {% if target_article.writer == user %}
      <a href="{% url 'articleapp:update' pk=target_article.pk %}"
      class="btn btn-primary rounded-pill col-3 mt-3">
        Update
      </a>
      <a href="{% url 'articleapp:delete' pk=target_article.pk %}"
      class="btn btn-secondary rounded-pill col-3 mt-3">
        Delete
      </a>
      {% endif %}
      <hr>

      {% for comment in target_article.comment.all %}
        {% include 'commentapp/detail.html' with comment=comment %}
      {% endfor %}

      {% include 'commentapp/create.html' with article=target_article %}
    </div>
  </div>

{% endblock %}

articleapp/templates/articleapp/list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <style>
        .container {
          padding: 0;
          margin: 0, auto;
        }

        .container a {
          width: 45%;
          max-width: 250px;
        }

        .container div {
          display: flex;
          justify-content: center;
          align-items: center;
          border-radius: 1rem;
        }

        .container img {
            width: 100%;
            border-radius: 1rem;
        }

    </style>

    {% if article_list %}
    <div class="container">
      {% for article in article_list %}
        <a href="{% url 'articleapp:detail' pk=article.pk %}">
            {% include 'snippets/card.html' with article=article %}
            <span>
                <span style="font-weight: bold">#{{ article.project.title }}</span>
                <span>
                    <i style="vertical-align: middle; font-size: 1.2rem; margin: 0 .5em;"
                    class="material-icons">
                        chat_bubble_outline
                    </i>
                    {{ article.comment.count }}
                </span>
                <span>
                    <i style="vertical-align: middle; font-size: 1.2rem; margin: 0 .5em;"
                    class="material-icons">
                        thumb_up_off_alt
                    </i>
                    {{ article.like }}
                </span>
            </span>
        </a>

      {% endfor %}
    </div>
    <script src="{% static 'js/magicgrid.js' %}"></script>
    {% else %}
                    {% if q %}
                    <tr class="text-center">
                        <td style="font-weight: bold; color:gray;" colspan="5">
                            <i class="fas fa-info-circle"></i>&nbsp;일치하는 검색 결과가 없습니다.
                        </td>
                    </tr>
                    {% else %}
                        <tr class="text-center">
                            <td style="font-weight: bold; color:gray;" colspan="5">
                                <i class="fas fa-info-circle"></i>&nbsp;작성된 게시글이 없습니다.
                            </td>
                        </tr>
                    {% endif %}
    {% endif %}

    <div class="container my-3" style="margin-top: 30px;">
        <form action="" method="GET">
            <div class="col">
                <div style="float: right;">
                    <div class="form-row">
                        <div class="col" style="margin-top: 10px;">
                            <select style="width: 6em;" class="custom-select custom-select-md" name="type">
                                <option value="all">전체</option>
                                <option value="title_content">제목+내용</option>
                                <option value="title">제목</option>
                                <option value="content">내용</option>
                                <option value="writer">작성자</option>
                            </select>
                        </div>
                        <div class="col" style="margin-top: 10px;">
                            <input type="text" name="q" value="{{ q }}" class="form-control form-control-md"
                                style="width: 15em;" placeholder="검색어를 입력해주세요.">
                        </div>
                        <div class="col" style="margin-top: 10px;">
                            <button class="btn btn-md btn-outline-dark" type="submit">검색</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div>
        {% if is_paginated %}
        <ul class="pagination justify-content-center" style="margin-bottom: 0;">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?type={{ type }}&q={{ q }}&page={{ page_obj.previous_page_number }}"
                    tabindex="-1">이전</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">이전</a>
            </li>
            {% endif %}

            {% for page in page_range %}
            <li class="page-item {% if page == page_obj.number %} activate {% endif %}">
                <a class="page-link" href="?type={{ type }}&q={{ q }}&page={{ page }}">{{ page }}</a>
            </li>
            {% endfor %}

            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link"
                    href="?type={{ type }}&q={{ q }}&page={{ page_obj.next_page_number }}">다음</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#">다음</a>
            </li>
            {% endif %}
        </ul>
        {% endif %}
    </div>

    <div style="text-align: center">
        <a href="{% url 'articleapp:create' %}" class="btn btn-dark rounded-pill col-3 mt-3 px-2">
            Ask a Question
        </a>
    </div>

{% endblock %}

articleapp/templates/articleapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">

    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>Question Update</h4>
        </div>
        <form action="{% url 'articleapp:update' pk=target_article.pk %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-3 mt-3">
        </form>
    </div>

<script>var editor = new MediumEditor('.editable');</script>

{% endblock %}